#!/bin/sh

MODDIR=/lib/modules
PinkPanelPath=/usr/lib/enigma2/python/Plugins/Extensions/PinkPanel
echo "init frontpanel"
#insmod $MODDIR/vfd.ko
insmod $MODDIR/aotom.ko
insmod $MODDIR/simu_button.ko
[ -e $MODDIR/encrypt.ko ] && insmod $MODDIR/encrypt.ko

if [ -e /var/etc/.firstboot ]; then
	echo "WAIT 1 min" >/dev/vfd
	echo "WAIT 1 min"
	rm /var/etc/.firstboot
	touch /dev/.devfsd
fi

rm -f /etc/.start_spark >/dev/null 2>&1

if [ -f /etc/.start_enigma2 ] && [ -e /usr/local/bin/enigma2 ]
then
	START_E2=1
elif [ -e /usr/local/bin/neutrino ]
then
	START_NEUTRINO=1
elif [ -e /usr/local/bin/enigma2 ]
then
	START_E2=1
fi

if [ -n "$START_E2" ]
then
	eval `egrep '^config\.(psi|plugins\.PinkPanel)\.' /etc/enigma2/settings | tr . _ `
fi

startVideoTuneEnhanced() {
	until [ -e /proc/stb/video/plane/psi_contrast ] ; do sleep 1 ; done

	[ -z "$config_psi_contrast" ] && config_psi_contrast=128
	[ -z "$config_psi_saturation" ] && config_psi_saturation=128
	[ -z "$config_psi_brightness" ] && config_psi_brightness=128
	[ -z "$config_psi_hue" ] && config_psi_hue=128
	
	echo $config_psi_contrast > /proc/stb/video/plane/psi_contrast
	echo $config_psi_saturation > /proc/stb/video/plane/psi_saturation
	echo $config_psi_brightness > /proc/stb/video/plane/psi_brightness
	echo $config_psi_hue > /proc/stb/video/plane/psi_tint
}

dualTuner() {
if [ ! -e /dev/dvb/adapter1 ]; then
	mkdir /dev/dvb/adapter1
	mknod /dev/dvb/adapter1/video0 c 212 64
	mknod /dev/dvb/adapter1/audio0 c 212 65
	mknod /dev/dvb/adapter1/frontend0 c 212 67
	mknod /dev/dvb/adapter1/demux0 c 212 68
	mknod /dev/dvb/adapter1/dvr0 c 212 69
	mknod /dev/dvb/adapter1/ca0 c 212 70
	ln -s /dev/dvb/adapter1/ca0 /dev/dvb/adapter1/ca1
	mknod /dev/dvb/adapter1/net0 c 212 71
	mknod /dev/dvb/adapter1/osd0 c 212 72
fi
if [ ! -e /var/run/mumudvb ]; then
	mkdir -p /var/run/mumudvb
fi
insmod $MODDIR/dvb-usb.ko
insmod $MODDIR/dvb-pll.ko
insmod $MODDIR/mt2060.ko
insmod $MODDIR/mxl5005s.ko
insmod $MODDIR/qt1010.ko
insmod $MODDIR/tda18218.ko
insmod $MODDIR/tda18271.ko
insmod $MODDIR/af9013.ko
insmod $MODDIR/dvb-usb-af9015.ko
}

/etc/init.d/mountvirtfs start
/etc/init.d/portmap start
(cd /dev/dvb/adapter0 && ln -sf ca0 ca1) &
(if [ -e /media/net ]; then rm -rf /media/net;fi;ln -sf /mnt/nfs /media/net) &
awk -f /etc/init.d/getfb.awk /dev/input/event1 &

insmod $MODDIR/e2_proc.ko
insmod $MODDIR/autofs4.ko

if [ ! -e /var/etc/.firstboot ]; then

	echo "Starting DEBUG Interface"
	/etc/init.d/mountall start
	/etc/init.d/hostname start
	# echo "starting telnetd vsftpd inetd mountall"
	/usr/sbin/telnetd -l /bin/login
	/etc/init.d/vsftpd start
	/usr/sbin/inetd
	echo "init stmfb"
	insmod $MODDIR/stmcore-display-sti7111.ko

	MEMSIZE=8m
	if [ -e /etc/.start_enigma2 ] ; then
		MEMSIZE=12m
		[ -e /etc/.15m ] && MEMSIZE=15m
	fi	
	isactive1=`cat /usr/local/share/config/neutrino.conf | grep video_Mode= | cut -d = -f2`
	if [ "$isactive1" = 2 ]; then
	        insmod $MODDIR/stmfb.ko display0=720x576-32@50:$MEMSIZE:pal:yuv:yuv;#SCART
	else
		insmod $MODDIR/stmfb.ko display0=1280x720-32@50:$MEMSIZE:pal:yuv:yuv;#HDMI
	fi

	echo "LOADING MODULES"   
	echo "LOAD" > /dev/vfd

	if [ -e /boot/audio.elf ] && [ -e /boot/video.elf ]; then
		echo "load a firmware"
		/bin/ustslave /dev/st231-1 /boot/audio.elf
		echo "load v firmware"
		/bin/ustslave /dev/st231-0 /boot/video.elf
	else
		echo "FIRMWARE MISSING (*.elf) !!!"
	fi

	[ -e $MODDIR/cpu_frequ.ko ] && insmod $MODDIR/cpu_frequ.ko

	echo "init embx"
	insmod $MODDIR/embxshell.ko
	insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0 ;
	insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000 ;
	insmod $MODDIR/mme_host.ko transport0=shm
	echo "init AVS"
	# insmod $MODDIR/avs.ko type=spark_avs
	insmod $MODDIR/avs.ko type=avs_pio
	player=`cat /proc/stb/player/version`
	echo "init player $player"

	insmod $MODDIR/mmelog.ko
	insmod $MODDIR/ksound.ko
	insmod $MODDIR/p2div64.ko
	insmod $MODDIR/stm_v4l2.ko
	insmod $MODDIR/stmvout.ko
	insmod $MODDIR/stmvbi.ko
	insmod $MODDIR/pseudocard.ko
	insmod $MODDIR/stv090x.ko
	insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
	insmod $MODDIR/stm_monitor.ko
	insmod $MODDIR/stmsysfs.ko
	#   whichSTM=`uname -a | grep stm23`
	#   if [ -z "$whichSTM" ]; then
	#      insmod $MODDIR/stmdvb.ko TSsource0=0
	#   else
	insmod $MODDIR/stmdvb.ko
	#   fi
	#   insmod $MODDIR/player2.ko
	insmod $MODDIR/player2.ko discardlateframe=0
	insmod $MODDIR/sth264pp.ko
	insmod $MODDIR/stmalloc.ko
	insmod $MODDIR/platform.ko
	insmod $MODDIR/silencegen.ko
	insmod $MODDIR/bpamem.ko
	mknod /dev/bpamem c 153 0 
	insmod $MODDIR/smartcard.ko

	[ -n "$START_E2" ] && eplayer3 /boot/startup.mp4 &

	stfbcontrol a 0
	whichbox=`cat /proc/cmdline | grep "hwaddr:" | awk -F "hwaddr:" '{print $2}' | cut -f1 -d " " | cut -f3 -d ":"`
	case $whichbox in
		07|08)
			echo "RC-default"
			;;
		*) [ -e /bin/evremote2.amiko ] && rm /bin/evremote2 && mv /bin/evremote2.amiko /bin/evremote2
		   [ -e /etc/lircd.conf.amiko ] && rm /etc/lircd.conf && mv /etc/lircd.conf.amiko /etc/lircd.conf;;
	esac
	echo "init lircd"
	/usr/bin/lircd
	/usr/bin/irexec -d /etc/lircrc

	mknod /dev/rc c 147 1 2>/dev/null
	mknod /dev/sci0 c 169 0 2>/dev/null

	major=$(awk "\$2==\"sparkid\" {print \$1}" /proc/devices)
	[ -n "$major" ] && {
		rm -f /dev/sparkid
		mknod /dev/sparkid c $major 0 
	}

	echo 1 > /proc/sys/kernel/panic

	( sleep 5; /usr/sbin/automount --timeout=30 /media file /etc/auto.usb) &
	( sleep 10
	  if [ ! -e /media/hdd/epg]; then
		cd /media/hdd && mkdir movie music picture swap epg
	  fi
	) &

	# /bin/evremote2 05 30 &

	if [ -n "$START_E2" ]; then
		[ -z "$config_plugins_PinkPanel_RCid" ] && config_plugins_PinkPanel_RCid=10
		[ -z "$config_plugins_PinkPanel_RCrd" ] && config_plugins_PinkPanel_RCrd=120
		/bin/evremote2 $config_plugins_PinkPanel_RCid $config_plugins_PinkPanel_RCrd &
		rm -f /etc/.extdisplay >/dev/null 2>&1
	else
		/bin/evremote2 &
	fi

	[ -e /etc/.dualTuner ] && [ -e /etc/.start_enigma2 ] && dualTuner &
	[ -e /etc/.fritzcall ] && (sleep 20; /var/plugins/fritzcall/fb.sh start) &
	[ -e /etc/.extdisplay ] && [ ! -e /etc/.start_enigma2 ] && (sleep 20; /etc/init.d/extDisplay.sh) &
	# green led off

	(sleep 10;/bin/fp_control -l 1 0) &

	if [ -n "$START_E2" ]
	then
		PLL0=/proc/cpu_frequ/pll0_ndiv_mdiv
		[ -e $PLL0 ] && [ -n "$config_plugins_PinkPanel_oclock" ] && echo $(($config_plugins_PinkPanel_oclock/10 * 256 + 3)) > $PLL0
	fi

	stfbcontrol a 255

	### eth start ###
	NFS=`grep -c nfs /proc/cmdline`
	if [ "$NFS" -eq "1" ]; then
	      echo "Booting from nfs, don't set network"
	else
		/etc/init.d/setupETH.sh &
	fi

	if [ -n "$START_NEUTRINO" ]; then
		if [ -e /etc/.EVOfirstboot ]; then
			echo "SCART 1 JA EXIT" > /dev/vfd
			TASTE=`hexdump -n 12 /dev/input/event1 | awk '{print $7}'`
			TASTE=`hexdump -n 12 /dev/input/event1 | awk '{print $7}'`
			case $TASTE in
				0002) mv /usr/local/share/config/neutrino.conf /usr/local/share/config/neutrino.conf.hdmi
					mv /usr/local/share/config/neutrino.conf.scart /usr/local/share/config/neutrino.conf
					echo "SCART aktiv" > /dev/vfd;;
				*) if [ -e /usr/local/share/config/neutrino.conf.hdmi ]; then
					mv /usr/local/share/config/neutrino.conf /usr/local/share/config/neutrino.conf.scart
					mv /usr/local/share/config/neutrino.conf.hdmi /usr/local/share/config/neutrino.conf
				fi
				echo "HDMI aktiv" > /dev/vfd;;
			esac
			sleep 3
			rm /etc/.EVOfirstboot
		fi
		isactive2=`cat /usr/local/share/config/neutrino.conf | grep video_Mode= | cut -d = -f2`
		if [ "$isactive2" = 2 ]; then #2=pal by osd!
			stfbcontrol rf cc cy cs #hd=hdmi-off, rf=full-rgb, fa=adaptive flicker on, cc=cvbs-out on, cr=component-out on
			pzapit --pal
		fi
	fi

	[ -n "$START_NEUTRINO" ] && [ -e /etc/.time ] && (sleep 20; /etc/init.d/DisplayTime.sh) &

	[ -e /usr/script/user_script.sh ] && /usr/script/user_script.sh &

	[ -n "$START_E2" ] && (sleep 15;startVideoTuneEnhanced) &
	
	#neutrinoTuxtxt=`cat /usr/local/share/config/neutrino.conf | grep video_Mode= | cut -d = -f2`
	#if [ $neutrinoTuxtxt == "7" ]; then
	#   ln -sf /usr/local/share/config/tuxtxt/tuxtxt2_720.conf /usr/local/share/config/tuxtxt/tuxtxt2.conf
	#else
	#   ln -sf /usr/local/share/config/tuxtxt/tuxtxt2_1080.conf /usr/local/share/config/tuxtxt/tuxtxt2.conf
	#fi
	/etc/init.d/Swap.sh &

	echo "run" > /dev/vfd
	if [ -n "$START_E2" ]; then
		echo "LOADING E2"

		until false
		do
			echo "starting e2->"
			/usr/local/bin/enigma2
			rtv=$?
			echo "e2 ended <- RTV: " $rtv
			case "$rtv" in
			0)	echo "$rtv"
			   echo "E2 ERROR"
			   killall -9 enigma2;;
			1)	echo "$rtv"
				echo "SHUTDOWN"
				sync
				HDDON=`mount | grep sda1 | cut -d " " -f5`
				if [ ! -z "$HDDON" ] && [ -e /etc/.fsck ]; then
					echo "hdd-check"
					echo "FSCK" > /dev/vfd
					umount /dev/sda1
					fsck.$HDDON -y /dev/sda1
				fi
				init 0;;
			2)	echo "$rtv"
				echo "REBOOT"
				init 6;;
			3)	echo "$rtv"
				echo "E2 RESTART"
				#echo "0" > /proc/progress;;
				#killall -9 enigma2;;
				sync
				killall enigma2;;
			*)	echo "*"
				echo "ERROR"
				echo "0" > /proc/progress;;
			esac
		done 
	else
		echo "LOADING neutrino"

		until false
		do
			echo "starting neutrino ->"
			/usr/local/bin/neutrino -f -u
			rtv=$?
			echo "neutrino ended <- RTV: " $rtv
			case "$rtv" in
			0|1)	echo "$rtv"
				echo "SHUTDOWN"
				sync
				HDDON=`mount | grep sda1 | cut -d " " -f5`
				if [ ! -z "$HDDON" ] && [ -e /etc/.fsck ]; then
					echo "hdd-check"
					echo "FSCK" > /dev/vfd
					umount /dev/sda1
					fsck.$HDDON -y /dev/sda1
				fi
				init 0;;
			2)	echo "$rtv"
				echo "REBOOT"
				sync
				init 6;;
			*) echo "$rtv"
				echo "ERROR"
				#echo "0" > /proc/progress;;
				init 6;;
			esac
		done 
	fi
fi

#never reached
echo "REBOOT PINGULUX" > /dev/vfd
echo "REBOOT PINGULUX"
reboot -f

