#!/bin/sh
# /etc/init.d/cam
MYCAMS="oscam mgcamd camd3"
MYBINPATH="/usr/bin"
MYCONFPATH="/usr/keys"
MYCAM2=""
MYCONFOPTIONS2=""
if [ -e $MYBINPATH/oscam ] && [ ! -e $MYBINPATH/mgcamd ] && [ ! -e $MYBINPATH/camd3 ]; then
	MYCAM="oscam"
	MYCONFOPTIONS="-b -c $MYCONFPATH"
elif [ -e $MYBINPATH/mgcamd ] && [ ! -e $MYBINPATH/camd3 ] && [ ! -e $MYBINPATH/oscam ]; then
	MYCAM="mgcamd"
	MYCONFOPTIONS="-c $MYCONFPATH/mg_cfg"
elif [ -e $MYBINPATH/mgcamd ] && [ -e $MYBINPATH/camd3 ] && [ ! -e $MYBINPATH/oscam ]; then
	MYCAM="mgcamd"
	MYCAM2="camd3"
	MYCONFOPTIONS="-c $MYCONFPATH/mg_cfg"
	MYCONFOPTIONS2="-C $MYCONFPATH/camd3.config"
fi

start() {
	if [ -z "$MYCAM2" ]; then
		($MYBINPATH/$MYCAM $MYCONFOPTIONS;sleep 2;/usr/local/bin/pzapit -rz >/dev/null 2>&1 &) &
	else
		($MYBINPATH/$MYCAM2 $MYCONFOPTIONS2;$MYBINPATH/$MYCAM $MYCONFOPTIONS;sleep 2;/usr/local/bin/pzapit -rz >/dev/null 2>&1 &) &
	fi
}

stop() {
	(for i in $MYCAMS
	do
	pkill $i
	done
	echo "$i stopped") &
}

# Carry out specific functions when asked to by the system
case "$1" in
	init)
		start;;
	stop)
		stop;;
	restart)
		(stop
		sleep 2
		start
		echo "$i restarted") &;;
	*)
		echo "Usage: /etc/init.d/cam {init|stop|restart}"
	exit 1;;
esac
exit 0
