#!/bin/sh
#
# nfs-kernel-server
#		This shell script takes care of starting and stopping
#               the kernel-mode NFS server.
#
# chkconfig: 2345 20 80
PATH=/bin:/usr/bin:/sbin:/usr/sbin
# description: NFS is a popular protocol for file sharing across TCP/IP \
#              networks. This service provides NFS server functionality, \
#              which is configured via the /etc/exports file.
#

set -e

# What is this?
DESC="NFS kernel daemon"
PREFIX=/usr

# Exit if required binaries are missing.
[ -x $PREFIX/sbin/rpc.nfsd ] || exit 0
[ -x $PREFIX/sbin/rpc.mountd ] || exit 0
[ -x $PREFIX/sbin/exportfs ] || exit 0

# Read config
DEFAULTFILE=/etc/default/nfs-kernel-server
#RPCNFSDCOUNT=8
RPCNFSDCOUNT=4
RPCMOUNTDOPTS=
if [ -f $DEFAULTFILE ]; then
    . $DEFAULTFILE
fi

# See how we were called.
case "$1" in
  start)
	cd /	# daemons should have root dir as cwd
	if [ -f /etc/exports ];	then
		$PREFIX/sbin/rpc.nfsd 4
		$PREFIX/sbin/rpc.statd
		$PREFIX/sbin/rpc.mountd
		$PREFIX/sbin/exportfs -a

	else
		echo "Not starting $DESC: No exports."
	fi
	;;

  stop)
	printf "Stopping $DESC: mountd"
	start-stop-daemon --stop --oknodo --quiet \
	    --name rpc.mountd --user 0
	printf " nfsd"
	start-stop-daemon --stop --oknodo --quiet \
	    --name nfsd --user 0 --signal 2
	echo "."

	printf "Unexporting directories for $DESC..."
	$PREFIX/sbin/exportfs -au
	echo "done."
	;;

  reload | force-reload)
	printf "Re-exporting directories for $DESC..."
	$PREFIX/sbin/exportfs -r
	echo "done."
	;;

  restart)
	$0 stop
	sleep 1
	$0 start
	;;

  *)
	echo "Usage: nfs-kernel-server {start|stop|reload|force-reload|restart}"
	exit 1
	;;
esac

exit 0
