#!/bin/sh

MODDIR=/lib/modules
echo "init frontpanel"
insmod $MODDIR/encrypt.ko
insmod $MODDIR/vfd.ko
insmod $MODDIR/aotom.ko

if [ -e /var/etc/.firstboot ]; then
   echo "WAIT 1 min" >/dev/vfd
   echo "WAIT 1 min"
   rm /var/etc/.firstboot
   touch /dev/.devfsd
fi

/etc/init.d/mountvirtfs start
/etc/init.d/portmap start

insmod $MODDIR/e2_proc.ko

# start automounter with umount timeout of 5 seconds
insmod $MODDIR/autofs4.ko
/usr/sbin/automount --timeout=5 /autofs file /etc/auto.usb

if [ ! -e /var/etc/.firstboot ]; then

   echo "Starting DEBUG Interface"
   /etc/init.d/mountall start
   /etc/init.d/hostname start

   echo "starting telnetd"
   /usr/sbin/telnetd -l /bin/login
   insmod $MODDIR/simu_button.ko
   echo "init lircd"
   /usr/bin/lircd
   echo "init stmfb"
   insmod $MODDIR/stmcore-display-sti7111.ko
   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:12m:pal:yuv:yuv

   echo "LOADING MODULES"   
   echo "LOAD" > /dev/vfd

   echo "load a firmware"
   /bin/ustslave /dev/st231-1 /boot/audio.elf
   echo "load v firmware"
   /bin/ustslave /dev/st231-0 /boot/video.elf

   echo "init embx"
   insmod $MODDIR/embxshell.ko
   insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0 ;
   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000 ;
   insmod $MODDIR/mme_host.ko transport0=shm

   echo "init AVS"
   insmod $MODDIR/avs.ko type=spark_avs

   player=`cat /proc/stb/player/version`
   echo "init player $player"

   insmod $MODDIR/mmelog.ko
   insmod $MODDIR/ksound.ko
   insmod $MODDIR/p2div64.ko
   insmod $MODDIR/stm_v4l2.ko
   insmod $MODDIR/stmvout.ko
   insmod $MODDIR/stmvbi.ko
   insmod $MODDIR/pseudocard.ko
   insmod $MODDIR/stv090x.ko
   insmod $MODDIR/pti.ko  waitMS=20 videoMem=4096
   insmod $MODDIR/stm_monitor.ko
   insmod $MODDIR/stmsysfs.ko
   insmod $MODDIR/stmdvb.ko
   insmod $MODDIR/player2.ko discardlateframe=0
   insmod $MODDIR/sth264pp.ko
   insmod $MODDIR/stmalloc.ko
   insmod $MODDIR/platform.ko
   insmod $MODDIR/silencegen.ko
#   insmod $MODDIR/smartcard.ko

   insmod $MODDIR/bpamem.ko
   mknod /dev/bpamem c 153 0 

   eplayer3 /boot/startup.mp4 &
   stfbcontrol a 0



   mknod /dev/rc c 147 1
   major=$(awk "\$2==\"sparkid\" {print \$1}" /proc/devices)
   rm -f /dev/sparkid
   mknod /dev/sparkid c $major 0 

   /bin/evremote2 spark &

   stfbcontrol a 255

   /etc/init.d/mountall start
   /etc/init.d/hostname start

   echo "starting telnetd"
   /usr/sbin/telnetd -l /bin/login
   /etc/init.d/vsftpd start
   /usr/sbin/inetd

   NFS=`grep -c nfs /proc/cmdline`
   if [ "$NFS" -eq "1" ]; then 
      echo "Booting from nfs, don't set network" 
   else 
      if [ -e /etc/network/interfaces ]; then 
	 ip addr flush eth0 
	 /etc/init.d/networking stop 
	 DHCP=`grep -c dhcp /etc/network/interfaces`
	 if [ "$DHCP" -eq "1" ]; then 
	    echo "Starting dhcp"
            /etc/init.d/udhcpc start 
	 fi 
	 /etc/init.d/networking start 
      fi 
   fi

   echo "run" > /dev/vfd
   echo "LOADING E2"

   until false
   do
      echo "starting e2->"
      /usr/local/bin/enigma2
      rtv=$?
      echo "e2 ended <- RTV: " $rtv
      case "$rtv" in
		0) echo "0"
		   echo "E2 ERROR"
      		   reboot;;
		1) echo "1"
		   echo "SHUTDOWN"
                   sync
                   umount -a;;
		2) echo "2"
		   echo "REBOOT"
		   reboot;;
		3) echo "3"
		   echo "E2 RESTART"
		   echo "0" > /proc/progress;;
		*) echo "*"
		   echo "ERROR"
		   echo "0" > /proc/progress;;
      esac
   done 
fi

#never reached
echo "REBOOT PINGULUX" > /dev/vfd
echo "REBOOT PINGULUX"
reboot -f

