#!/bin/sh
e2path=/devel/E2/release884flash
pythonpath=$e2path/usr/lib/python2.6
cd $e2path
rm -rf $pythonpath/lib-dynload/_testcapi.so
rm -rf $pythonpath/lib-dynload/cmath.so
rm -rf $pythonpath/lib-dynload/mmap.so
rm -rf $pythonpath/lib-dynload/strop.so
rm -rf $pythonpath/site-packages/twisted/internet/_dumbwin32proc.pyc
rm -rf $pythonpath/site-packages/twisted/internet/_win32serialport.pyc
rm -rf $pythonpath/site-packages/twisted/internet/_win32stdio.pyc
rm -rf $pythonpath/site-packages/twisted/internet/test
rm -rf $pythonpath/site-packages/twisted/internet/test/__init__.pyc
rm -rf $pythonpath/site-packages/twisted/internet/test/test_gtk2reactor.pyc
rm -rf $pythonpath/site-packages/twisted/internet/test/test_iocp.pyc
rm -rf $pythonpath/site-packages/twisted/python/_epoll.pyx
rm -rf $pythonpath/site-packages/twisted/python/test
rm -rf $pythonpath/site-packages/twisted/python/test/__init__.pyc
rm -rf $pythonpath/site-packages/twisted/python/test/test_components.pyc
rm -rf $pythonpath/site-packages/twisted/python/test/test_deprecate.pyc
rm -rf $pythonpath/site-packages/twisted/python/test/test_dist.pyc
rm -rf $pythonpath/site-packages/twisted/python/test/test_release.pyc
rm -rf $pythonpath/site-packages/twisted/python/test/test_util.pyc
rm -rf $pythonpath/site-packages/twisted/python/test/test_versions.pyc
rm -rf $pythonpath/site-packages/twisted/python/test/test_zipstream.pyc
#rm -rf $pythonpath/site-packages/twisted/web
rm -rf $pythonpath/site-packages/twisted/web2/test
rm -rf $pythonpath/site-packages/twisted/web2/test/__init__.pyc
rm -rf $pythonpath/site-packages/twisted/web2/test/server.pem
rm -rf $pythonpath/site-packages/twisted/web2/test/simple_client.pyc
rm -rf $pythonpath/site-packages/twisted/web2/test/test_cgi.pyc
rm -rf $pythonpath/site-packages/twisted/web2/test/test_client.pyc
rm -rf $pythonpath/site-packages/twisted/web2/test/test_compat.pyc
rm -rf $pythonpath/site-packages/twisted/web2/test/test_fastcgi.pyc
rm -rf $pythonpath/site-packages/twisted/web2/test/test_fileupload.pyc
rm -rf $pythonpath/site-packages/twisted/web2/test/test_http.pyc
rm -rf $pythonpath/site-packages/twisted/web2/test/test_http_headers.pyc
rm -rf $pythonpath/site-packages/twisted/web2/test/test_httpauth.pyc
rm -rf $pythonpath/site-packages/twisted/web2/test/test_log.pyc
rm -rf $pythonpath/site-packages/twisted/web2/test/test_plugin.pyc
rm -rf $pythonpath/site-packages/twisted/web2/test/test_resource.pyc
rm -rf $pythonpath/site-packages/twisted/web2/test/test_scgi.pyc
rm -rf $pythonpath/site-packages/twisted/web2/test/test_server.pyc
rm -rf $pythonpath/site-packages/twisted/web2/test/test_static.pyc
rm -rf $pythonpath/site-packages/twisted/web2/test/test_stream.pyc
rm -rf $pythonpath/site-packages/twisted/web2/test/test_vhost.pyc
rm -rf $pythonpath/site-packages/twisted/web2/test/test_wsgi.pyc
rm -rf $pythonpath/site-packages/twisted/web2/test/test_xmlrpc.pyc
rm -rf $pythonpath/site-packages/zope/interface/DEPENDENCIES.cfg
rm -rf $pythonpath/site-packages/zope/interface/PUBLICATION.cfg
rm -rf $pythonpath/site-packages/zope/interface/SETUP.cfg
rm -rf $pythonpath/site-packages/zope/interface/common
rm -rf $pythonpath/site-packages/zope/interface/common/__init__.pyc
rm -rf $pythonpath/site-packages/zope/interface/common/idatetime.pyc
rm -rf $pythonpath/site-packages/zope/interface/common/interfaces.pyc
rm -rf $pythonpath/site-packages/zope/interface/common/mapping.pyc
rm -rf $pythonpath/site-packages/zope/interface/common/sequence.pyc
rm -rf $pythonpath/site-packages/zope/interface/common/tests
rm -rf $pythonpath/site-packages/zope/interface/common/tests/__init__.pyc
rm -rf $pythonpath/site-packages/zope/interface/common/tests/basemapping.pyc
rm -rf $pythonpath/site-packages/zope/interface/common/tests/test_idatetime.py
rm -rf $pythonpath/site-packages/zope/interface/tests
rm -rf $pythonpath/site-packages/zope/interface/tests/__init__.pyc
rm -rf $pythonpath/site-packages/zope/interface/tests/dummy.pyc
rm -rf $pythonpath/site-packages/zope/interface/tests/ifoo.pyc
rm -rf $pythonpath/site-packages/zope/interface/tests/m1.pyc
rm -rf $pythonpath/site-packages/zope/interface/tests/m2.pyc
rm -rf $pythonpath/site-packages/zope/interface/tests/odd.pyc
rm -rf $pythonpath/site-packages/zope/interface/tests/test_adapter.pyc
rm -rf $pythonpath/site-packages/zope/interface/tests/test_advice.pyc
rm -rf $pythonpath/site-packages/zope/interface/tests/test_declarations.pyc
rm -rf $pythonpath/site-packages/zope/interface/tests/test_document.pyc
rm -rf $pythonpath/site-packages/zope/interface/tests/test_element.pyc
rm -rf $pythonpath/site-packages/zope/interface/tests/test_interface.pyc
rm -rf $pythonpath/site-packages/zope/interface/tests/test_odd_declarations.py
rm -rf $pythonpath/site-packages/zope/interface/tests/test_sorting.pyc
rm -rf $pythonpath/site-packages/zope/interface/tests/test_verify.pyc
rm -rf $pythonpath/site-packages/zope/interface/tests/unitfixtures.pyc
exit
