--- a/Makefile	2012-06-23 12:20:45.000000000 +0200
+++ b/Makefile	2012-06-24 09:43:12.000000000 +0200
@@ -20,8 +20,8 @@
 MANDIR  ?= $(PREFIX)/share/man
 BINDIR  ?= $(PREFIX)/bin
 INCDIR  ?= $(PREFIX)/include
-LOCDIR  ?= $(PREFIX)/share/locale
-LIBS     = -ljpeg -lpthread -ldl -lrt -lexpat -lfreetype -lfontconfig $(shell pkg-config --libs freetype2 fontconfig)
+LOCDIR  ?= ./locale
+LIBS     = -ljpeg -lpthread -ldl -lcap -lrt $(shell pkg-config --libs freetype2 fontconfig)
 INCLUDES ?= $(shell pkg-config --cflags freetype2 fontconfig)
 
 PLUGINDIR= ./PLUGINS
@@ -42,10 +42,14 @@
 
 OBJS = audio.o channels.o ci.o config.o cutter.o device.o diseqc.o dvbdevice.o dvbci.o\
        dvbplayer.o dvbspu.o dvbsubtitle.o eit.o eitscan.o epg.o filter.o font.o i18n.o interface.o keys.o\
-       lirc.o menu.o menuitems.o nit.o osdbase.o osd.o pat.o player.o plugin.o rcu.o\
+       lirc.o menu.o menuitems.o nit.o osdbase.o osd.o pat.o player.o plugin.o\
        receiver.o recorder.o recording.o remote.o remux.o ringbuffer.o sdt.o sections.o shutdown.o\
-       skinclassic.o skins.o skinsttng.o sourceparams.o sources.o spu.o status.o svdrp.o themes.o thread.o\
-       timers.o tools.o transfer.o vdr.o videodir.o tinystr.o tinyxml.o tinyxmlerror.o tinyxmlparser.o submenu.o
+       skinclassic.o skinlcars.o skins.o skinsttng.o sourceparams.o sources.o spu.o status.o svdrp.o themes.o thread.o\
+       timers.o tools.o transfer.o vdr.o videodir.o
+
+ifdef SETUP
+OBJS += tinystr.o tinyxml.o tinyxmlerror.o tinyxmlparser.o submenu.o
+endif
 
 ifndef NO_KBD
 DEFINES += -DREMOTE_KBD
@@ -224,8 +228,8 @@
 
 install-pc: vdr.pc
 	if [ -n "$(PCDIR)" ] ; then \
-	    mkdir -p $(PCDIR) ; \
-	    cp vdr.pc $(PCDIR) ; \
+	    mkdir -p $(DESTDIR)$(PCDIR) ; \
+	    cp vdr.pc $(DESTDIR)$(PCDIR) ; \
 	    fi
 
 # Source documentation:
